# Generated code do not commit.
file(TO_CMAKE_PATH "D:\\UNIVERSITY_DOCUMENTATIONS\\DART LAB AND PROJECT\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "D:\\ERDATA_home" PROJECT_DIR)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=D:\\UNIVERSITY_DOCUMENTATIONS\\DART LAB AND PROJECT\\flutter"
  "PROJECT_DIR=D:\\ERDATA_home"
  "FLUTTER_ROOT=D:\\UNIVERSITY_DOCUMENTATIONS\\DART LAB AND PROJECT\\flutter"
  "FLUTTER_EPHEMERAL_DIR=D:\\ERDATA_home\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=D:\\ERDATA_home"
  "FLUTTER_TARGET=D:\\ERDATA_home\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=D:\\ERDATA_home\\.dart_tool\\package_config.json"
)
