# Generated by Django 4.0.2 on 2022-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('photos', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('bank_account', models.CharField(max_length=40)),
                ('kebele', models.CharField(max_length=30)),
                ('woreda', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=50)),
                ('regesterd_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
