# Generated by Django 4.0.2 on 2022-05-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erdata_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
