# Generated by Django 4.0.2 on 2022-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erdata_app', '0005_remove_children_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='children',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='children',
            name='age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
